# Generated by Django 5.1.3 on 2025-01-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('toDo', 'To Do'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='toDo', max_length=10),
        ),
    ]
